# Generated by Django 5.0.4 on 2024-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
