# Generated by Django 5.0.4 on 2024-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_values', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_values', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
