# Generated by Django 5.0.4 on 2024-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=60)),
            ],
        ),
    ]
