# Generated by Django 5.0.4 on 2024-09-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
