# Generated by Django 5.0.4 on 2024-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipment_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='equipment',
            name='assignment_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=20),
        ),
    ]
