# Generated by Django 5.0.4 on 2024-09-07 12:17

import equipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_equipment_condition_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=equipments.models.Equipment.get_condition_choices, default='NEW & WORKING', max_length=40),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=equipments.models.Equipment.get_status_choices, default='AVAILABLE', max_length=20),
        ),
    ]
