# Generated by Django 5.0.4 on 2024-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_equipment_condition_alter_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
