# Generated by Django 5.0.4 on 2024-09-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_equipment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
    ]
