# Generated by Django 5.0.4 on 2024-09-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_remove_equipment_location_remove_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
