# Generated by Django 5.0.4 on 2024-09-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignees', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_type', models.CharField(max_length=20)),
                ('assigned_date', models.DateTimeField()),
                ('letter_for_issue', models.CharField(max_length=200)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_condition', models.CharField(choices=[('NEW', 'NEW'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], max_length=20)),
                ('returned_condition', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], max_length=20)),
                ('letter_for_return', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignees.assignee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
        ),
    ]
