# Generated by Django 5.0.4 on 2024-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='letter_for_issue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='letter_for_return',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
