# Generated by Django 5.0.4 on 2024-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_assigned_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='issue_person_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='issue_person_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_person_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_person_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
