# Generated by Django 5.0.4 on 2024-09-17 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_issue_person_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_details',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
