# Generated by Django 5.0.4 on 2024-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=20)),
            ],
        ),
    ]
