# Generated by Django 5.0.4 on 2024-09-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignees', '0001_initial'),
        ('assignments', '0003_alter_assignment_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_person_type', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('original_date_of_hire', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_class', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_nontech', models.CharField(blank=True, max_length=50, null=True)),
                ('oic_no', models.PositiveIntegerField(blank=True, null=True)),
                ('oic_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('division_code', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('circle_code', models.PositiveIntegerField(blank=True, null=True)),
                ('circle', models.CharField(blank=True, max_length=255, null=True)),
                ('region_code', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('org_code', models.PositiveIntegerField(blank=True, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Assignee',
        ),
    ]
