# Generated by Django 5.0.4 on 2024-09-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignees', '0002_employee_location_vendor_delete_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='circle',
            new_name='circle_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='division',
            new_name='division_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='region',
            new_name='region_name',
        ),
    ]
