# Generated by Django 5.0.4 on 2024-09-02 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=20)),
                ('po_type', models.CharField(max_length=100, null=True)),
                ('project_id', models.CharField(blank=True, max_length=20, null=True)),
                ('project_name', models.CharField(blank=True, max_length=150, null=True)),
                ('supplier_id', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
